# Only the scheduled daily job uses this private, userspace VPN.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.services.mirror;
  vpn = cfg.vpn;
  upstream = cfg.package;
  proxy = "http://127.0.0.1:${toString vpn.port}";
  profile = pkgs.writeText "mirror-vpn.sb" ''
    (version 1)
    (allow default)
    (deny network*)
    (deny mach-lookup (global-name "com.apple.mDNSResponder"))
    (deny mach-lookup (global-name "com.apple.dnssd.service"))
    (allow network-outbound (remote ip "localhost:${toString vpn.port}"))
    (allow network-outbound
      (literal "${cfg.postgresql.socketDir}/.s.PGSQL.${toString cfg.postgresql.port}")
      (literal "${lib.optionalString (lib.hasPrefix "/tmp" cfg.postgresql.socketDir) "/private"}${cfg.postgresql.socketDir}/.s.PGSQL.${toString cfg.postgresql.port}"))
  '';
  daily = pkgs.writeShellScript "mirror-daily-vpn-steps" ''
    set -eu
    ${upstream}/bin/mirror ${
      lib.escapeShellArgs (
        [
          "discover"
          "--limit"
          (toString cfg.jobs.discover.limit)
        ]
        ++ cfg.jobs.discover.extraArgs
      )
    }
    ${upstream}/bin/mirror ${
      lib.escapeShellArgs (
        [
          "fetch"
          "--limit"
          (toString cfg.jobs.daily.limit)
        ]
        ++ cfg.jobs.fetch.extraArgs
      )
    }
    ${upstream}/bin/mirror ${
      lib.escapeShellArgs (
        [
          "recheck"
          "--limit"
          (toString cfg.jobs.recheck.limit)
          "--older-than"
          cfg.jobs.recheck.olderThan
          "--verify"
          (toString cfg.jobs.recheck.verify)
        ]
        ++ cfg.jobs.recheck.extraArgs
      )
    }
  '';
  protectedDaily = pkgs.writeShellScript "mirror-daily-vpn" ''
    set -eu
    if [ -n "''${MIRROR_ENV_FILE:-}" ] && [ -r "$MIRROR_ENV_FILE" ]; then
      set -a
      . "$MIRROR_ENV_FILE"
      set +a
    fi
    export http_proxy=${lib.escapeShellArg proxy}
    export https_proxy="$http_proxy" HTTP_PROXY="$http_proxy" HTTPS_PROXY="$http_proxy"
    export all_proxy="$http_proxy" ALL_PROXY="$http_proxy" no_proxy= NO_PROXY=
    if ! /usr/bin/sandbox-exec -f ${profile} ${pkgs.curl}/bin/curl \
      --silent --fail --proxy "$http_proxy" --noproxy "" \
      --connect-timeout 5 --max-time 20 --output /dev/null https://ip.me; then
      echo 'mirror daily: VPN unavailable; acquisition stopped (no direct fallback).' >&2
      exit 75
    fi
    exec /usr/bin/sandbox-exec -f ${profile} ${daily}
  '';
in
{
  options.services.mirror.vpn = {
    enable = lib.mkEnableOption "VPN for the mirror daily job with blocked direct traffic";
    configFile = lib.mkOption {
      type = lib.types.str;
      default = "${cfg.home}/.config/mirror/vpn.json";
      description = "Private sing-box config, generated by mirror-vpn-import outside the Nix store.";
    };
    port = lib.mkOption {
      type = lib.types.port;
      default = 17890;
      description = "Loopback HTTP proxy port (must match the imported config).";
    };
  };

  config = lib.mkIf (cfg.enable && vpn.enable) {
    launchd.user.agents.mirror-daily.command = lib.mkForce protectedDaily;
    launchd.user.agents.mirror-vpn = {
      command = pkgs.writeShellScript "mirror-vpn" ''
        set -eu
        if [ ! -r ${lib.escapeShellArg vpn.configFile} ]; then
          echo 'mirror VPN: import a Proton WireGuard config with mirror-vpn-import.' >&2
          exit 78
        fi
        exec ${pkgs.sing-box}/bin/sing-box run -c ${lib.escapeShellArg vpn.configFile}
      '';
      serviceConfig = {
        KeepAlive = true;
        RunAtLoad = true;
        ThrottleInterval = 30;
        StandardOutPath = "${cfg.logDir}/mirror-vpn.log";
        StandardErrorPath = "${cfg.logDir}/mirror-vpn.log";
      };
    };
  };
}
