#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
nix flake update
if command -v darwin-rebuild &>/dev/null; then
  sudo darwin-rebuild switch --flake .
else
  sudo nix run nix-darwin -- switch --flake .
fi
